"""Initial migration

Revision ID: 6a458a116f11
Revises: 
Create Date: 2025-10-19 17:55:50.074569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a458a116f11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_id'), table_name='feature')
    op.drop_table('feature')
    op.drop_index(op.f('ix_building_point_name'), table_name='building_point')
    op.drop_table('building_point')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_images_name'), table_name='images')
    op.drop_index(op.f('ix_images_path'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('path', sa.VARCHAR(), nullable=False),
    sa.Column('calculated_camera_locations', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_path'), 'images', ['path'], unique=False)
    op.create_index(op.f('ix_images_name'), 'images', ['name'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('building_point',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_point_name'), 'building_point', ['name'], unique=False)
    op.create_table('feature',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pixel_x', sa.INTEGER(), nullable=False),
    sa.Column('pixel_y', sa.INTEGER(), nullable=False),
    sa.Column('building_point_id', sa.INTEGER(), nullable=False),
    sa.Column('image_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['building_point_id'], ['building_point.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_id'), 'feature', ['id'], unique=False)
    # ### end Alembic commands ###
